export const PROPOSAL_STATUS = {
  PROPOSAL_STATUS_DEPOSIT_PERIOD: "DEPOSIT",
  PROPOSAL_STATUS_VOTING_PERIOD: "VOTING",
  PROPOSAL_STATUS_PASSED: "PASSED",
  PROPOSAL_STATUS_REJECTED: "REJECTED",
  PROPOSAL_STATUS_FAILED: "FAILED",
  PROPOSAL_STATUS_INVALID: "INVALID",
};
