export const HANDLE_LOGIN_MODAL = "HANDLE_LOGIN_MODAL";
export const HANDLE_NEWWALLET_MODAL = "HANDLE_NEWWALLET_MODAL";
export const HANDLE_RECOVERMNEMONIC_MODAL = "HANDLE_RECOVERMNEMONIC_MODAL";
export const HANDLE_IMPORTPRIVATEKEY_MODAL = "HANDLE_IMPORTPRIVATEKEY_MODAL";
export const HANDLE_CONNECTLEDGER_MODAL = "HANDLE_CONNECTLEDGER_MODAL";
