export const HANDLE_MODAL_RESET = "HANDLE_MODAL_RESET";
export const HANDLE_MODAL_DATA = "HANDLE_MODAL_DATA";

export const HANDLE_MODAL_PAPERWALLET = "HANDLE_MODAL_PAPERWALLET";
export const HANDLE_MODAL_QRCODE = "HANDLE_MODAL_QRCODE";
export const HANDLE_MODAL_NETWORK = "HANDLE_MODAL_NETWORK";
export const HANDLE_MODAL_LOGIN = "HANDLE_MODAL_LOGIN";
export const HANDLE_MODAL_SETTINGS = "HANDLE_MODAL_SETTINGS";
export const HANDLE_MODAL_NEWWALLET = "HANDLE_MODAL_NEWWALLET";
export const HANDLE_MODAL_CONFIRMWALLET = "HANDLE_MODAL_CONFIRMWALLET";
export const HANDLE_MODAL_RECOVERMNEMONIC = "HANDLE_MODAL_RECOVERMNEMONIC";
export const HANDLE_MODAL_IMPORTPRIVATEKEY = "HANDLE_MODAL_IMPORTPRIVATEKEY";
export const HANDLE_MODAL_EXPORTPRIVATEKEY = "HANDLE_MODAL_EXPORTPRIVATEKEY";
export const HANDLE_MODAL_EXPORTMNEMONIC = "HANDLE_MODAL_EXPORTMNEMONIC";
export const HANDLE_MODAL_CHANGEPASSWORD = "HANDLE_MODAL_CHANGEPASSWORD";
export const HANDLE_MODAL_CONNECTLEDGER = "HANDLE_MODAL_CONNECTLEDGER";

export const HANDLE_MODAL_DELEGATE = "HANDLE_MODAL_DELEGATE";
export const HANDLE_MODAL_REDELEGATE = "HANDLE_MODAL_REDELEGATE";
export const HANDLE_MODAL_UNDELEGATE = "HANDLE_MODAL_UNDELEGATE";
export const HANDLE_MODAL_DEPOSIT = "HANDLE_MODAL_DEPOSIT";
export const HANDLE_MODAL_VOTING = "HANDLE_MODAL_VOTING";
export const HANDLE_MODAL_NEWPROPOSAL = "HANDLE_MODAL_NEWPROPOSAL";
export const HANDLE_MODAL_SEND = "HANDLE_MODAL_SEND";

export const HANDLE_MODAL_CONFIRMTX = "HANDLE_MODAL_CONFIRMTX";
export const HANDLE_MODAL_QUEUETX = "HANDLE_MODAL_QUEUETX";
export const HANDLE_MODAL_RESULTTX = "HANDLE_MODAL_RESULTTX";
export const HANDLE_MODAL_GASESTIMATION = "HANDLE_MODAL_GASESTIMATION";

export const HANDLE_WALLET_ADDRESS = "HANDLE_WALLET_ADDRESS";
export const HANDLE_WALLET_TIMEKEY = "HANDLE_WALLET_TIMEKEY";
export const HANDLE_WALLET_INIT = "HANDLE_WALLET_INIT";
export const HANDLE_WALLET_LEDGER = "HANDLE_WALLET_LEDGER";

export const HANDLE_USER_BALANCE = "HANDLE_USER_BALANCE";
export const HANDLE_USER_VESTING = "HANDLE_USER_VESTING";
export const HANDLE_USER_TOKEN_LIST = "HANDLE_USER_TOKEN_LIST";
export const HANDLE_USER_NFT_LIST = "HANDLE_USER_NFT_LIST";
