const colors = {
  backgroundSideBar: "#1B1C22",
  activeBackground: "#323232",
  backgroundBlack: "#131317",
  defaultWhite: "#929fed",
  defaultGray: "#eeeeee",
  defaultGray2: "#bbb",
  defaultGray3: "#ddd",
  defaultGray4: "#808080",
  defaultGray5: "#444",
  defaultGray6: "#777",
  defaultDarkGray: "#aaa",
  defaultFont: "#8285af",
  defaultGrayFont: "#707070",
  realWhite: "#ffffff",
  borderLine: "#34353c",

  default1: "#647dae",
  default2: "#aa647b",
  default3: "#d32f2f",
  default4: "#f57c00",
  default5: "#1976d2",
  default6: "#388e3c",

  buttonBackground: "#1e2650",
  buttonBorder: "#324ab8",

  mainblue: "#3550DE",
  mainpurple: "#502CBA",
  mainskyblue: "#1FBAFF",
  mainred: "#D8424A",
  mainyellow: "#F4B017",
  maingreen: "#47EC9F",
};

const sizes = {
  sideMenu: "1.6rem",
  sideMenuIcon: "2rem",
  defaultSize: "1.6rem",
  singleCardTitle: "1.4rem",
  singleCardContent: "3.2rem",
  footerContent: "1.2rem",
  headerContent: "1.3rem",
  headerAddress: "1.2rem",
  headerTypo: "1.7rem",
  pieChartLabel: "1.4rem",
  logout: "1.7rem",
  stakingSmall: "1.2rem",
  stakingSemiMedium: "1.3rem",
  stakingMedium: "1.4rem",
  stakingLarge: "1.6rem",
  stakingXLarge: "1.8rem",
  stakingXXLarge: "2.2rem",
  stakingXXXLarge: "2.4rem",
  accountCardSize1: "1.8rem",
  accountCardSize2: "1.4rem",
  accountCardSize3: "1.6rem",
  accountCardSize4: "1.4rem",
  accountCardSize5: "1.2rem",
  stakingCardSize1: "1.6rem",
  stakingCardSize2: "2.0rem",
  depositCardSize1: "1.6rem",
  depositCardSize2: "1.8rem",
  depositCardSize3: "2.0rem",
  proposalDetailCardSize1: "2.0rem",
  proposalDetailCardSize2: "1.6rem",
  votingCardSize1: "1.6rem",
  votingCardSize2: "1.8rem",
  votingCardSize3: "2.0rem",
  proposalTitle: "2.0rem",
  proposalCardSize1: "2.0rem",
  proposalCardSize2: "1.6rem",
  modalTitle: "2.4rem",
  modalButton: "2.2rem",
  modalLabel: "1.6rem",
  modal14: "1.4rem",
  modal15: "1.45rem",
  modal16: "1.6rem",
  modal18: "1.8rem",
  modalIcon: "3rem",
  modalTypo: "1.6rem",
  tokenomicsDetail: "1.6rem",
  votingpowerSize1: "3.0rem",
  votingpowerSize2: "1.8rem",
  votingpowerSize3: "1.6rem",
  comingTitle: "5.0rem",
  communityTitle: "4.0rem",
  communitySubTitle: "2.0rem",
  sideMenuDrawer: "210px",
};

const urls = {
  logo: process.env.PUBLIC_URL + "/images/white_logo.svg",
  bgLogo: process.env.PUBLIC_URL + "/images/bgLogo.png",
  fullLogo: process.env.PUBLIC_URL + "/images/firma_chain_title.svg",
  qr: process.env.PUBLIC_URL + "/images/qr.png",
  telegram: process.env.PUBLIC_URL + "/images/ic_telegram.svg",
  github: process.env.PUBLIC_URL + "/images/ic_github.svg",
  twitter: process.env.PUBLIC_URL + "/images/ic_twitter.svg",
  medium: process.env.PUBLIC_URL + "/images/ic_medium.svg",
  profile: process.env.PUBLIC_URL + "/images/profile.png",
  ledger: process.env.PUBLIC_URL + "/images/ledger.png",
  paperwallet: process.env.PUBLIC_URL + "/images/paperwallet.png",
  close: process.env.PUBLIC_URL + "/images/ic_close.png",
  tooltip: process.env.PUBLIC_URL + "/images/ic_tooltip.png",
  win: process.env.PUBLIC_URL + "/images/icon_win.png",
  linux: process.env.PUBLIC_URL + "/images/icon_linux.png",
  mac: process.env.PUBLIC_URL + "/images/icon_mac.png",
  on: process.env.PUBLIC_URL + "/images/on.png",
  off: process.env.PUBLIC_URL + "/images/off.png",
  sortIdle: process.env.PUBLIC_URL + "/images/sort_idle.png",
  sortASC: process.env.PUBLIC_URL + "/images/sort_asc.png",
  sortDESC: process.env.PUBLIC_URL + "/images/sort_desc.png",
};

const theme = {
  colors,
  sizes,
  urls,
};

export default theme;
