const colors = {
  backgroundSideBar: "#1B1C22",
  activeBackground: "#323232",
  backgroundBlack: "#131317",
  defaultWhite: "#929fed",
  defaultGray: "#eeeeee",
  defaultGray2: "#bbb",
  defaultGray3: "#ddd",
  defaultGray4: "#808080",
  defaultGray5: "#444",
  defaultGray6: "#777",
  defaultDarkGray: "#aaa",
  defaultFont: "#8285af",
  defaultGrayFont: "#707070",
  realWhite: "#ffffff",
  borderLine: "#34353c",

  default1: "#647dae",
  default2: "#aa647b",
  default3: "#d32f2f",
  default4: "#f57c00",
  default5: "#1976d2",
  default6: "#388e3c",

  buttonBackground: "#1e2650",
  buttonBorder: "#324ab8",

  mainblue: "#3550DE",
  mainpurple: "#502CBA",
  mainskyblue: "#1FBAFF",
  mainred: "#D8424A",
  mainyellow: "#F4B017",
  maingreen: "#47EC9F",
};

const sizes = {
  sideMenu: "16px",
  singleCardTitle: "14px",
  singleCardContent: "32px",
  footerContent: "12px",
  headerContent: "13px",
  accountCardSize1: "18px",
  accountCardSize2: "11px",
  accountCardSize3: "16px",
  accountCardSize4: "14px",
  accountCardSize5: "12px",
  stakingCardSize1: "16px",
  stakingCardSize2: "20px",
  depositCardSize1: "16px",
  depositCardSize2: "18px",
  depositCardSize3: "20px",
  proposalDetailCardSize1: "20px",
  proposalDetailCardSize2: "16px",
  votingCardSize1: "16px",
  votingCardSize2: "18px",
  votingCardSize3: "20px",
  proposalCardSize1: "20px",
  proposalCardSize2: "16px",
  sideMenuDrawer: "230px",
  modalTitle: "20px",
  modalLabel: "16px",
  tokenomicsDetail: "16px",
  votingpowerSize1: "30px",
  votingpowerSize2: "18px",
  votingpowerSize3: "16px",
};

const urls = {
  logo: process.env.PUBLIC_URL + "/images/white_logo.svg",
  bgLogo: process.env.PUBLIC_URL + "/images/bgLogo.png",
  fullLogo: process.env.PUBLIC_URL + "/images/firma_chain_title.svg",
  qr: process.env.PUBLIC_URL + "/images/qr.png",
  telegram: process.env.PUBLIC_URL + "/images/ic_telegram.svg",
  github: process.env.PUBLIC_URL + "/images/ic_github.svg",
  twitter: process.env.PUBLIC_URL + "/images/ic_twitter.svg",
  medium: process.env.PUBLIC_URL + "/images/ic_medium.svg",
};

const theme = {
  colors,
  sizes,
  urls,
};

export default theme;
